import { AlertTriangle, Search } from "lucide-react";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { MotionPage } from "@/components/ui/motion";
import { KnowledgeDocumentCard } from "@/features/knowledge-base/knowledge-document-card";
import { KnowledgeEmptyState } from "@/features/knowledge-base/knowledge-empty-state";
import { KnowledgeSearchResults } from "@/features/knowledge-base/knowledge-search-results";
import { KnowledgeUploadForm } from "@/features/knowledge-base/knowledge-upload-form";
import type { KnowledgeDocumentListItem, KnowledgeSearchResult } from "@/features/knowledge-base/queries";

export function KnowledgeWorkspace({ canManage, documents, searchError, searchQuery, searchResults, stats }: { canManage: boolean; documents: KnowledgeDocumentListItem[]; searchError: string | null; searchQuery: string; searchResults: KnowledgeSearchResult[]; stats: { chunks: number; failed: number; ready: number; total: number } }) {
  return <MotionPage className="mx-auto grid max-w-7xl gap-6 px-5 py-8 md:px-8 xl:grid-cols-[300px_1fr]"><aside className="space-y-5"><Card className="ai-premium-surface overflow-hidden"><CardHeader><Badge>Base documental</Badge><CardTitle className="text-2xl">Conhecimento da empresa</CardTitle><p className="text-sm leading-6 text-muted-strong">Envie documentos, processe chunks e use busca semântica com isolamento por organização.</p></CardHeader><CardContent className="grid grid-cols-2 gap-3"><Metric label="Documentos" value={stats.total.toString()} /><Metric label="Prontos" value={stats.ready.toString()} /><Metric label="Chunks" value={stats.chunks.toString()} /><Metric label="Falhas" value={stats.failed.toString()} /></CardContent></Card><KnowledgeUploadForm canManage={canManage} />{!canManage ? <Card className="border-warning/50 bg-panel-elevated"><CardContent className="flex items-start gap-3 p-4"><AlertTriangle className="mt-0.5 size-4 text-warning" /><div><p className="text-sm font-medium">Modo somente leitura</p><p className="mt-1 text-sm leading-6 text-muted-strong">Membros podem consultar documentos, mas apenas owners e admins podem enviar novos arquivos.</p></div></CardContent></Card> : null}</aside><section className="min-w-0 space-y-6"><div><Badge>Busca semântica</Badge><h1 className="mt-4 text-4xl font-semibold tracking-normal">Documentos prontos para IA</h1><p className="mt-3 max-w-2xl text-base leading-7 text-muted-strong">Pesquise nos chunks vetorizados e acompanhe status de ingestão, falhas e volume processado por documento.</p><form className="mt-5 flex flex-col gap-3 rounded-[var(--radius-panel)] border border-panel-border bg-panel p-3 sm:flex-row"><label className="relative min-w-0 flex-1"><Search className="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted" /><input className="h-11 w-full rounded-[var(--radius-control)] border border-panel-border bg-panel-elevated pl-10 pr-3 text-sm outline-none transition placeholder:text-muted focus:border-primary" defaultValue={searchQuery} name="q" placeholder="Buscar por política, cliente, procedimento..." /></label><Button type="submit"><Search className="size-4" />Buscar</Button></form></div>{searchQuery ? <KnowledgeSearchResults error={searchError} query={searchQuery} results={searchResults} /> : null}<div className="space-y-4">{documents.length ? documents.map((document) => <KnowledgeDocumentCard canManage={canManage} document={document} key={document.id} />) : <KnowledgeEmptyState canManage={canManage} />}</div></section></MotionPage>;
}

function Metric({ label, value }: { label: string; value: string }) {
  return <div className="rounded-md border border-panel-border bg-panel-elevated px-3 py-3"><p className="text-xs uppercase tracking-[0.08em] text-muted">{label}</p><p className="mt-2 font-mono text-2xl text-primary">{value}</p></div>;
}
