import { QrCode, Radio, Trash2 } from "lucide-react";
import { PageHeader, PageLayout } from "@/components/app";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { getRequiredWorkspace } from "@/features/organizations/queries";
import { deleteConnectionAction, updateConnectionAction } from "@/features/support/actions";
import { ConnectionForm } from "@/features/support/connection-form";
import { listChannelConnections } from "@/features/support/queries";

export default async function ChannelsPage(){const workspace=await getRequiredWorkspace();const connections=await listChannelConnections(workspace.organization.id);const canManage=["owner","admin"].includes(workspace.membership.role);return <PageLayout size="wide" className="space-y-7"><PageHeader eyebrow="Infraestrutura de atendimento" title="Canais" description="CRUD, conexao e estado de cada numero. Oficial e nao oficial nunca compartilham sessao ou credencial."/><div className="grid gap-6 xl:grid-cols-[320px_1fr]"><Card><CardHeader><CardTitle>Novo canal</CardTitle></CardHeader><CardContent><ConnectionForm canManage={canManage}/></CardContent></Card><section className="space-y-3">{connections.map((connection)=><Card key={connection.id}><CardContent className="space-y-4 p-4 md:pt-4"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex gap-3"><span className="flex size-10 items-center justify-center rounded-md bg-sidebar-active text-primary">{connection.authMethod==="qr"?<QrCode className="size-5"/>:<Radio className="size-5"/>}</span><div><p className="font-medium">{connection.name}</p><p className="mt-1 text-xs text-muted">{connection.phoneNumber}</p></div></div><div className="flex gap-2"><Badge>{connection.kind==="official"?"Oficial":"Nao oficial"}</Badge><Button disabled size="sm" variant="secondary">Fornecedor pendente</Button></div></div>{canManage?<details className="border-t border-panel-border pt-3"><summary className="cursor-pointer text-sm text-primary">Editar canal</summary><form action={updateConnectionAction.bind(null,connection.id)} className="mt-3 grid gap-2 md:grid-cols-[1fr_180px_150px_auto]"><input className="h-9 rounded-md border border-panel-border bg-panel-elevated px-3 text-sm" defaultValue={connection.name} name="name"/><input className="h-9 rounded-md border border-panel-border bg-panel-elevated px-3 text-sm" defaultValue={connection.phoneNumber} name="phone"/><select className="h-9 rounded-md border border-panel-border bg-panel-elevated px-2 text-sm" defaultValue={connection.authMethod} name="authMethod"><option value="qr">QR Code</option><option value="pin">PIN Code</option></select><Button size="sm" type="submit">Salvar</Button></form><form action={deleteConnectionAction.bind(null,connection.id)} className="mt-3"><Button type="submit" variant="danger"><Trash2 className="size-4"/>Excluir canal</Button></form></details>:null}</CardContent></Card>)}</section></div></PageLayout>}
